### ISSUE TITLE
Failed to load the sofistik-tools package

### ISSUE THREAD

**Issue by crystalfalls** [bacadra/pulsar-sofistik-tools#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Education
**Thrown From**: [sofistik-tools](https://github.com/bacadra/atom-sofistik-tools) package 0.1.16

### Stack Trace

Failed to load the sofistik-tools package

```
At Cannot find module 'atom-select-list'
Require stack:
- C:\Users\lech\.atom\packages\sofistik-tools\lib\help-view.js
- C:\Users\lech\.atom\packages\sofistik-tools\lib\main.js
- C:\Users\lech\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-select-list'
Require stack:
- C:\Users\lech\.atom\packages\sofistik-tools\lib\help-view.js
- C:\Users\lech\.atom\packages\sofistik-tools\lib\main.js
- C:\Users\lech\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/sofistik-tools/lib/help-view.js:17:23)
    at /packages/sofistik-tools/lib/help-view.js:12:30)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/sofistik-tools/lib/main.js:3:43)
    at /packages/sofistik-tools/lib/main.js:298:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3507053
    at Package.measure (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3505853)
    at Package.load (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3506626)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384186)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:382914)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385486)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:915033
    at r (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:909639)
    at n (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1194945)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -1:38.9.0 snippets:show (ul.list-inline.tab-bar.inset-panel)
  2x -1:14.2.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:48.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
sofistik-language 0.3.2 
sofistik-tools 0.1.16 
```

**Comment by asiloisad** [comment]
I have updated the dependencies. Can you try install the package again?

**Comment by crystalfalls** [comment]
Sure. Thx for update :D
